# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_BnpGsC2UMtyXNwR5KYJM8s4JZrLpsp
"""

# БЛОК 1 - ЯДРО СИСТЕМЫ БЕЗ ТОРМОЗОВ
!pip install python-telegram-bot apscheduler pytz
import datetime, asyncio, json, pytz, re
from collections import Counter
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, KeyboardButton, ReplyKeyboardMarkup, ReplyKeyboardRemove
from telegram.ext import Application, CommandHandler, CallbackQueryHandler, MessageHandler, ContextTypes, filters
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger

# ОПТИМИЗИРОВАННАЯ КОНФИГУРАЦИЯ
CONFIG = {
    "token": "8281147294:AAEzOek15AiCN0ayZ79KAJjHYlScO-u5NhU",
    "admin_id": 5892547881,
    "masters": {"Анна": 5892547881, "Мария": 5892547881, "Иван": 5892547881},
    "salon_info": {
        "phone": "+7 (999) 123-45-67",
        "address": "ул. Центральная, 123",
        "working_hours": {"start": "09:00", "end": "21:00", "lunch": "13:00-14:00"}
    },
    "services": {"стрижка": 1000, "бритье": 500, "окрашивание": 2000, "укладка": 300}
}

# ОПТИМИЗИРОВАННЫЕ ХРАНИЛИЩА
bookings = {}
client_data = {}
user_sessions = {}
master_stats = {master: {"bookings": 0, "revenue": 0, "rating": 5.0} for master in CONFIG["masters"]}
master_schedules = {master: {"working_days": [0,1,2,3,4,5], "vacations": []} for master in CONFIG["masters"]}
analytics_data = {'service_popularity': Counter(), 'master_popularity': Counter(), 'time_preferences': Counter()}

# БЫСТРЫЕ ПАТТЕРНЫ ВМЕСТО AI
service_patterns = {'стрижка': r'(стрижк|подстрич)', 'бритье': r'(брит|бород)', 'окрашивание': r'(окраш|цвет)', 'укладка': r'(укладк|улож)'}
master_patterns = {'Анна': r'(анн|аня)', 'Мария': r'(мари|маша)', 'Иван': r'(иван|ваня)'}

print("✅ ЯДРО СИСТЕМЫ ЗАГРУЖЕНО БЕЗ ТОРМОЗОВ!")

# БЛОК 2 - ВИЗУАЛЬНЫЙ КАЛЕНДАРЬ И УМНОЕ РАСПИСАНИЕ
class UltraCalendar:
    def create_visual_calendar(self, year=None, month=None):
        today = datetime.date.today()
        year = year or today.year
        month = month or today.month

        # ЗАГОЛОВОК
        month_names = ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"]
        keyboard = [[InlineKeyboardButton(f"📅 {month_names[month-1]} {year}", callback_data="header")]]

        # ДНИ НЕДЕЛИ
        keyboard.append([InlineKeyboardButton(day, callback_data="header") for day in ["Пн","Вт","Ср","Чт","Пт","Сб","Вс"]])

        # ДАТЫ
        first_day = datetime.date(year, month, 1)
        last_day = datetime.date(year, month+1, 1) - datetime.timedelta(days=1) if month < 12 else datetime.date(year+1, 1, 1) - datetime.timedelta(days=1)

        current_row = []
        for _ in range(first_day.weekday()):
            current_row.append(InlineKeyboardButton(" ", callback_data="empty"))

        current_date = first_day
        while current_date <= last_day:
            if len(current_row) == 7:
                keyboard.append(current_row)
                current_row = []

            date_str = current_date.strftime("%Y-%m-%d")
            is_available = self.is_date_available(date_str)
            is_today = current_date == today

            emoji = "🔴" if not is_available else "🟢" if is_today else "⚪"
            btn = InlineKeyboardButton(f"{emoji}{current_date.day}", callback_data=f"date_{date_str}")
            current_row.append(btn)
            current_date += datetime.timedelta(days=1)

        if current_row:
            while len(current_row) < 7:
                current_row.append(InlineKeyboardButton(" ", callback_data="empty"))
            keyboard.append(current_row)

        # НАВИГАЦИЯ
        nav_row = []
        if month > 1 or year > today.year:
            prev_month = month-1 if month>1 else 12
            prev_year = year if month>1 else year-1
            nav_row.append(InlineKeyboardButton("◀️", callback_data=f"nav_{prev_year}_{prev_month}"))

        nav_row.append(InlineKeyboardButton("🗓️ Сегодня", callback_data="nav_today"))

        if month < 12 or year < today.year+1:
            next_month = month+1 if month<12 else 1
            next_year = year if month<12 else year+1
            nav_row.append(InlineKeyboardButton("▶️", callback_data=f"nav_{next_year}_{next_month}"))

        keyboard.append(nav_row)
        return InlineKeyboardMarkup(keyboard)

    def is_date_available(self, date_str):
        date_obj = datetime.datetime.strptime(date_str, "%Y-%m-%d").date()
        if date_obj.weekday() == 6: return False  # ВОСКРЕСЕНЬЕ

        for master in CONFIG["masters"]:
            # ПРОВЕРКА ОТПУСКА
            if any(vacation["start"] <= date_str <= vacation["end"] for vacation in master_schedules[master]["vacations"]):
                continue

            # ПРОВЕРКА СВОБОДНЫХ СЛОТОВ
            available_times = self.generate_available_times(date_str, master)
            if available_times: return True
        return False

    def generate_available_times(self, date_str, master):
        times = []
        start, end = datetime.datetime.strptime("09:00", "%H:%M"), datetime.datetime.strptime("21:00", "%H:%M")
        lunch_start, lunch_end = datetime.datetime.strptime("13:00", "%H:%M"), datetime.datetime.strptime("14:00", "%H:%M")

        current = start
        while current < end:
            if lunch_start <= current < lunch_end:
                current = lunch_end
                continue

            time_str = current.strftime("%H:%M")
            is_booked = any(b['date']==date_str and b['time']==time_str and b['master']==master and b['status']=='confirmed' for b in bookings.values())
            if not is_booked: times.append(time_str)
            current += datetime.timedelta(minutes=30)
        return times

class SmartScheduler:
    def set_master_vacation(self, master, start_date, end_date):
        master_schedules[master]["vacations"].append({"start": start_date, "end": end_date})
        self.cancel_vacation_bookings(master, start_date, end_date)

    def cancel_vacation_bookings(self, master, start_date, end_date):
        cancelled = []
        for bid, booking in bookings.items():
            if (booking["master"] == master and booking["status"] == "confirmed" and
                start_date <= booking["date"] <= end_date):
                bookings[bid]["status"] = "cancelled"
                cancelled.append(bid)
        return cancelled

ultra_calendar = UltraCalendar()
smart_scheduler = SmartScheduler()
print("✅ ВИЗУАЛЬНЫЙ КАЛЕНДАРЬ И РАСПИСАНИЕ ГОТОВЫ!")

# БЛОК 3 - ПОЛНЫЙ ФУНКЦИОНАЛ БЕЛА
async def start_booking(update: Update, context: ContextTypes.DEFAULT_TYPE):
    keyboard = [[InlineKeyboardButton(f"✂️ {service} - {price}₽", callback_data=f"service_{service}")]
                for service, price in CONFIG["services"].items()]
    await update.message.reply_text("✂️ ВЫБЕРИТЕ УСЛУГУ:", reply_markup=InlineKeyboardMarkup(keyboard))

async def handle_service(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    service = query.data.replace("service_", "")
    user_sessions[query.from_user.id] = {"service": service}

    keyboard = [[InlineKeyboardButton(f"👨‍💼 {master}", callback_data=f"master_{master}")] for master in CONFIG["masters"]]
    keyboard.append([InlineKeyboardButton("⬅️ Назад", callback_data="back_services")])

    await query.edit_message_text(f"✂️ УСЛУГА: {service}\n\nВЫБЕРИТЕ МАСТЕРА:", reply_markup=InlineKeyboardMarkup(keyboard))

async def handle_master(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()

    if query.data == "back_services":
        await start_booking(update, context)
        return

    master = query.data.replace("master_", "")
    user_id = query.from_user.id
    user_sessions[user_id]["master"] = master

    await query.edit_message_text(
        f"✂️ {user_sessions[user_id]['service']}\n👨‍💼 МАСТЕР: {master}\n\nВЫБЕРИТЕ ДАТУ:",
        reply_markup=ultra_calendar.create_visual_calendar()
    )

async def handle_calendar(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()

    if query.data.startswith("nav_"):
        if query.data == "nav_today":
            new_calendar = ultra_calendar.create_visual_calendar()
        else:
            parts = query.data.replace("nav_", "").split("_")
            new_calendar = ultra_calendar.create_visual_calendar(int(parts[0]), int(parts[1]))
        await query.edit_message_reply_markup(reply_markup=new_calendar)
        return

    if not query.data.startswith("date_"): return

    date_str = query.data.replace("date_", "")
    user_id = query.from_user.id
    user_sessions[user_id]["date"] = date_str
    master = user_sessions[user_id]["master"]

    times = ultra_calendar.generate_available_times(date_str, master)
    keyboard = []
    row = []
    for i, time_str in enumerate(times):
        row.append(InlineKeyboardButton(f"🕒 {time_str}", callback_data=f"time_{time_str}"))
        if len(row) == 3:
            keyboard.append(row)
            row = []
    if row: keyboard.append(row)
    keyboard.append([InlineKeyboardButton("⬅️ Назад", callback_data="back_calendar")])

    date_display = datetime.datetime.strptime(date_str, "%Y-%m-%d").strftime("%d.%m.%Y")
    await query.edit_message_text(
        f"✂️ {user_sessions[user_id]['service']}\n👨‍💼 {master}\n📅 {date_display}\n\nВЫБЕРИТЕ ВРЕМЯ:",
        reply_markup=InlineKeyboardMarkup(keyboard)
    )

async def handle_time(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()

    if query.data == "back_calendar":
        user_id = query.from_user.id
        session = user_sessions.get(user_id, {})
        await query.edit_message_text(
            f"✂️ {session.get('service','')}\n👨‍💼 {session.get('master','')}\n\nВЫБЕРИТЕ ДАТУ:",
            reply_markup=ultra_calendar.create_visual_calendar()
        )
        return

    time_str = query.data.replace("time_", "")
    user_id = query.from_user.id
    user_sessions[user_id]["time"] = time_str
    session = user_sessions[user_id]

    date_display = datetime.datetime.strptime(session["date"], "%Y-%m-%d").strftime("%d.%m.%Y")
    price = CONFIG["services"][session["service"]]

    confirm_text = f"✅ ПОДТВЕРЖДЕНИЕ ЗАПИСИ:\n\n✂️ {session['service']}\n👨‍💼 {session['master']}\n📅 {date_display}\n⏰ {time_str}\n💰 {price}₽\n\nВСЁ ВЕРНО?"

    keyboard = [[
        InlineKeyboardButton("✅ Подтвердить", callback_data="confirm_yes"),
        InlineKeyboardButton("❌ Отменить", callback_data="confirm_no")
    ]]
    await query.edit_message_text(confirm_text, reply_markup=InlineKeyboardMarkup(keyboard))

async def handle_confirmation(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()

    if query.data == "confirm_yes":
        user_id = query.from_user.id
        session = user_sessions[user_id]

        # СОЗДАЕМ ЗАПИСЬ
        booking_id = f"{user_id}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}"
        price = CONFIG["services"][session["service"]]

        bookings[booking_id] = {
            "id": booking_id, "user_id": user_id, "user_name": query.from_user.first_name,
            "service": session["service"], "master": session["master"], "date": session["date"],
            "time": session["time"], "price": price, "status": "confirmed",
            "created_at": datetime.datetime.now().isoformat()
        }

        # ОБНОВЛЯЕМ СТАТИСТИКУ
        master_stats[session["master"]]["bookings"] += 1
        master_stats[session["master"]]["revenue"] += price
        analytics_data['service_popularity'][session["service"]] += 1
        analytics_data['master_popularity'][session["master"]] += 1
        analytics_data['time_preferences'][session["time"]] += 1

        # СОБИРАЕМ ДАННЫЕ КЛИЕНТА
        if user_id not in client_data:
            client_data[user_id] = {"name": query.from_user.first_name, "username": query.from_user.username, "bookings_count": 0}
        client_data[user_id]["bookings_count"] += 1

        date_display = datetime.datetime.strptime(session["date"], "%Y-%m-%d").strftime("%d.%m.%Y")
        await query.edit_message_text(
            f"🎉 ЗАПИСЬ ПОДТВЕРЖДЕНА!\n\n✅ {session['service']}\n👨‍💼 {session['master']}\n📅 {date_display}\n⏰ {session['time']}\n💰 {price}₽\n\n📞 {CONFIG['salon_info']['phone']}"
        )

        # УВЕДОМЛЕНИЕ АДМИНА
        try:
            app = Application.builder().token(CONFIG["token"]).build()
            await app.bot.send_message(
                chat_id=CONFIG["admin_id"],
                text=f"🔔 НОВАЯ ЗАПИСЬ!\n{query.from_user.first_name}\n{session['service']}\n{session['master']}\n{date_display} {session['time']}"
            )
        except: pass

    else:
        await query.edit_message_text("❌ ЗАПИСЬ ОТМЕНЕНА")
        if query.from_user.id in user_sessions:
            del user_sessions[query.from_user.id]

# СИСТЕМА УПРАВЛЕНИЯ ЗАПИСЯМИ
async def my_bookings(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    user_bookings = [b for b in bookings.values() if b["user_id"] == user_id and b["status"] == "confirmed"]

    if not user_bookings:
        await update.message.reply_text("📭 НЕТ АКТИВНЫХ ЗАПИСЕЙ")
        return

    for booking in user_bookings:
        date_display = datetime.datetime.strptime(booking["date"], "%Y-%m-%d").strftime("%d.%m.%Y")
        text = f"✂️ {booking['service']}\n👨‍💼 {booking['master']}\n📅 {date_display}\n⏰ {booking['time']}\n💰 {booking['price']}₽"

        keyboard = [[
            InlineKeyboardButton("🔄 Перенести", callback_data=f"reschedule_{booking['id']}"),
            InlineKeyboardButton("❌ Отменить", callback_data=f"cancel_{booking['id']}")
        ]]
        await update.message.reply_text(text, reply_markup=InlineKeyboardMarkup(keyboard))

async def handle_management(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()

    if query.data.startswith("cancel_"):
        booking_id = query.data.replace("cancel_", "")
        bookings[booking_id]["status"] = "cancelled"
        await query.edit_message_text("✅ ЗАПИСЬ ОТМЕНЕНА")

    elif query.data.startswith("reschedule_"):
        booking_id = query.data.replace("reschedule_", "")
        user_sessions[query.from_user.id] = {"reschedule_id": booking_id, **bookings[booking_id]}
        await query.edit_message_text("🔄 ВЫБЕРИТЕ НОВУЮ ДАТУ:", reply_markup=ultra_calendar.create_visual_calendar())

# АДМИН ПАНЕЛЬ
async def admin_panel(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.effective_user.id != CONFIG["admin_id"]:
        await update.message.reply_text("⛔ ДОСТУП ЗАПРЕЩЕН")
        return

    today = datetime.date.today().strftime("%Y-%m-%d")
    today_bookings = [b for b in bookings.values() if b["date"] == today and b["status"] == "confirmed"]
    week_revenue = sum(b["price"] for b in bookings.values() if b["status"] == "confirmed")

    text = f"👑 АДМИН ПАНЕЛЬ\n\n📊 СЕГОДНЯ: {len(today_bookings)} зап.\n💰 НЕДЕЛЯ: {week_revenue}₽\n👥 КЛИЕНТОВ: {len(client_data)}\n\n"

    for master, stats in master_stats.items():
        text += f"👨‍💼 {master}: {stats['bookings']} зап., {stats['revenue']}₽, ★{stats['rating']}\n"

    # АНАЛИТИКА УСЛУГ
    popular_service = analytics_data['service_popularity'].most_common(1)
    if popular_service:
        text += f"\n🔥 ПОПУЛЯРНАЯ УСЛУГА: {popular_service[0][0]} ({popular_service[0][1]} раз)"

    await update.message.reply_text(text)

# ПАНЕЛЬ МАСТЕРА
async def master_panel(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    master_name = next((name for name, mid in CONFIG["masters"].items() if mid == user_id), None)
    if not master_name: return

    today = datetime.date.today().strftime("%Y-%m-%d")
    my_bookings = [b for b in bookings.values() if b["master"] == master_name and b["date"] == today and b["status"] == "confirmed"]

    text = f"👨‍💼 ПАНЕЛЬ {master_name}\n\n📅 СЕГОДНЯ:\n"
    for booking in sorted(my_bookings, key=lambda x: x["time"]):
        text += f"⏰ {booking['time']} - {booking['service']} ({booking['user_name']})\n"

    text += f"\n💰 ВЫРУЧКА: {master_stats[master_name]['revenue']}₽"
    await update.message.reply_text(text)

print("✅ ВЕСЬ ФУНКЦИОНАЛ РЕАЛИЗОВАН!")

# БЛОК 4 - ИСПРАВЛЕННЫЙ ЗАПУСК ДЛЯ COLAB
class RealReminderSystem:
    def __init__(self):
        self.scheduler = BackgroundScheduler()
        self.scheduler.start()
        self.setup_daily_tasks()

    def setup_daily_tasks(self):
        # ЕЖЕДНЕВНЫЕ НАПОМИНАНИЯ В 8 УТРА
        self.scheduler.add_job(self.schedule_reminders, 'cron', hour=8, minute=0)
        # ПРОВЕРКА ЗДОРОВЬЯ КАЖДЫЙ ЧАС
        self.scheduler.add_job(self.health_check, 'cron', hour='*', minute=0)

    def schedule_reminders(self):
        tomorrow = (datetime.datetime.now() + datetime.timedelta(days=1)).strftime("%Y-%m-%d")
        tomorrow_bookings = [b for b in bookings.values() if b["date"] == tomorrow and b["status"] == "confirmed"]

        for booking in tomorrow_bookings:
            # НАПОМИНАНИЕ ЗА 3 ЧАСА
            reminder_time = self.calculate_reminder_time(booking["time"], hours_before=3)
            self.scheduler.add_job(
                self.send_reminder, 'date', run_date=reminder_time,
                args=[booking['id'], '3_hours'], id=f"reminder_{booking['id']}_3h"
            )

    def calculate_reminder_time(self, booking_time, hours_before):
        booking_dt = datetime.datetime.strptime(booking_time, "%H:%M")
        reminder_dt = booking_dt - datetime.timedelta(hours=hours_before)
        return datetime.datetime.now().replace(hour=reminder_dt.hour, minute=reminder_dt.minute) + datetime.timedelta(days=1)

    async def send_reminder(self, booking_id, reminder_type):
        try:
            if booking_id not in bookings: return
            booking = bookings[booking_id]
            app = Application.builder().token(CONFIG["token"]).build()

            message = (f"🔔 НАПОМИНАНИЕ О ЗАПИСИ!\n\n⏰ {booking['time']} - {booking['service']}\n"
                      f"👨‍💼 {booking['master']}\n📍 {CONFIG['salon_info']['address']}\n📞 {CONFIG['salon_info']['phone']}")

            await app.bot.send_message(chat_id=booking['user_id'], text=message)
            print(f"✅ Напоминание отправлено {booking['user_name']}")
        except Exception as e:
            print(f"❌ Ошибка напоминания: {e}")

    def health_check(self):
        print(f"❤️ Проверка здоровья: {datetime.datetime.now()}")
        active = len([b for b in bookings.values() if b["status"] == "confirmed"])
        print(f"📊 Активных записей: {active}")

class AutoRestartBot:
    def __init__(self):
        self.restart_count = 0
        self.max_restarts = 50

    async def setup_handlers(self, app):
        app.add_handler(CommandHandler("start", start_booking))
        app.add_handler(CommandHandler("mybookings", my_bookings))
        app.add_handler(CommandHandler("admin", admin_panel))
        app.add_handler(CommandHandler("master", master_panel))

        app.add_handler(CallbackQueryHandler(handle_service, pattern="^service_"))
        app.add_handler(CallbackQueryHandler(handle_master, pattern="^(master_|back_services)"))
        app.add_handler(CallbackQueryHandler(handle_calendar, pattern="^(date_|nav_|back_calendar)"))
        app.add_handler(CallbackQueryHandler(handle_time, pattern="^time_"))
        app.add_handler(CallbackQueryHandler(handle_confirmation, pattern="^confirm_"))
        app.add_handler(CallbackQueryHandler(handle_management, pattern="^(cancel_|reschedule_)"))

    async def run_bot(self):
        """Запуск бота для Colab"""
        try:
            print("🔄 Создаю приложение бота...")
            app = Application.builder().token(CONFIG["token"]).build()
            await self.setup_handlers(app)

            # ЗАПУСКАЕМ НАПОМИНАНИЯ
            reminder_system = RealReminderSystem()

            print("🎉 БОТ ЗАПУЩЕН! КОМАНДЫ:")
            print("/start - запись, /mybookings - управления, /admin - админка, /master - мастер")
            print("⏹️  Для остановки нажмите Ctrl+C")

            # ЗАПУСКАЕМ ПОЛЛИНГ
            await app.run_polling()

        except Exception as e:
            print(f"❌ Ошибка запуска: {e}")
            return False
        return True

    async def run_forever(self):
        """Бесконечный перезапуск для Colab"""
        while self.restart_count < self.max_restarts:
            success = await self.run_bot()

            if not success:
                self.restart_count += 1
                if self.restart_count < self.max_restarts:
                    wait_time = min(2 ** self.restart_count, 300)
                    print(f"⏳ Перезапуск через {wait_time} сек... (попытка {self.restart_count + 1}/{self.max_restarts})")
                    await asyncio.sleep(wait_time)
                else:
                    print("🚨 Достигнут лимит перезапусков")
                    break
            else:
                # Если бот завершился без ошибки (например, ручная остановка)
                break

# ФИНАЛЬНЫЙ ЗАПУСК ДЛЯ COLAB
async def main_colab():
    bot = AutoRestartBot()
    await bot.run_forever()

print("🚀 ЗАПУСКАЮ ПОЛНУЮ СИСТЕМУ ДЛЯ COLAB...")

# ЗАПУСК В COLAB БЕЗ asyncio.run()
try:
    import nest_asyncio
    nest_asyncio.apply()

    # Запускаем в существующем loop
    loop = asyncio.get_event_loop()
    loop.create_task(main_colab())
    print("✅ Бот запущен в фоновом режиме!")
    print("📱 Переходи в Telegram и тестируй команды!")

except Exception as e:
    print(f"❌ Ошибка: {e}")
    print("🔄 Пробую альтернативный запуск...")

    # Альтернативный способ запуска
    async def quick_start():
        bot = AutoRestartBot()
        await bot.run_bot()

    # Прямой запуск
    import asyncio
    asyncio.ensure_future(quick_start())
    print("✅ Бот запущен!")